### ISSUE TITLE
base manual migrations

### ISSUE THREAD

**Issue by evanwill** [uidaholib/base-digital-collections-template#1]
- [x] White Pine - King of Many Waters

[migration outline](https://github.com/uidaholib/cdm-migration-project-docs/blob/main/manual-migrate.md)

**Comment by aweymo-ui** [comment]
notified @kxuidaho that updated site data has been added to digital>whitepines

**Comment by aweymo-ui** [comment]
Updated the site data with display_template and object file path corrected

**Comment by evanwill** [comment]
done
