### ISSUE TITLE
barstock "n.d." dates

### ISSUE THREAD

**Issue by evanwill** [uidaholib/base-digital-collections-template#11]
@kxuidaho @aweymo-ui new items added to barstock contain "n.d." as a date value. The "date" field should only contain ISO dates, no other text (i.e. "n.d." = blank). Please clean up these dates! If necessary create an "archival_date" field to hold the information.

**Comment by aweymo-ui** [comment]
I didn't find any time spans in the date range so I turned the n.d. to blanks, updated the csv and redeployed.
