### ISSUE TITLE
NW postcards manual migration

### ISSUE THREAD

**Issue by evanwill** [uidaholib/base-digital-collections-template#2]
Northwest Historical Postcards Collection, https://www.lib.uidaho.edu/digital/postcards/
Requires some careful metadata and object work. Currently 532 images (postcards with just front) and 279 pdfs (postcards with front and back). 

- [x] prep images from archive
- [x] change PDF items into "multiple" object type instead (i.e. two images not a pdf). this will involve creation of new rows with parentid. Each postcard will have a parent row with the full metadata, then two rows with the parentid which contain only the image links (front and back).

**Comment by kxuidaho** [comment]
all ready to go, just have to put the objects on the server!

**Comment by evanwill** [comment]
@kxuidaho can you put the objects on the new objects server (even though not usable yet)?

**Comment by evanwill** [comment]
done!
